
blockChain:
  url : https://eth-goerli.g.alchemy.com/v2/JPjmSUF1kvrZBv-cVGU5eaqP3Is0zSl6
  privateKey : '0xf66a4b5fc70231262c2afc9920a0bb594e963c1e677767b505e86e45861ed6a9'
  ws : wss://eth-goerli.g.alchemy.com/v2/JPjmSUF1kvrZBv-cVGU5eaqP3Is0zSl6