DROP TABLE IF EXISTS POST;

CREATE TABLE POST(
	ID INT PRIMARY KEY AUTO_INCREMENT
	, TITLE varchar(255)
	, DESCRIPTION text
	, AUTHRO text
	, CREATED_AT DATETIME DEFAULT CURRENT_TIMESTAMP
	, UPDATED_AT DATETIME DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP
);
